{
  "formatVersion": "1.1",
  "component": {
    "group": "de.kwerber",
    "module": "persistlib",
    "version": "0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.persistence",
          "module": "javax.persistence-api",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "persistlib-0.4.jar",
          "url": "persistlib-0.4.jar",
          "size": 60049,
          "sha512": "df0b9e4c96200699159d09b758eee6bd9c02ac78397c16ede70c7ad4ae4d8eeae3df900e2c14081bfcd4c96923591a93f524e57181d7b03b3d9744387c3e39ef",
          "sha256": "e0aeb0522f68d0fa6e7fe98d8504f7d2a905c22802353904ab94d0e8de0a35a3",
          "sha1": "4088593f3a3e32b7079b2e79764dd813ae26d2c1",
          "md5": "d79e43610995f598c93b1b1da4cff62b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.vorburger.mariaDB4j",
          "module": "mariaDB4j",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.mariadb.jdbc",
          "module": "mariadb-java-client",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "javax.persistence",
          "module": "javax.persistence-api",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "persistlib-0.4.jar",
          "url": "persistlib-0.4.jar",
          "size": 60049,
          "sha512": "df0b9e4c96200699159d09b758eee6bd9c02ac78397c16ede70c7ad4ae4d8eeae3df900e2c14081bfcd4c96923591a93f524e57181d7b03b3d9744387c3e39ef",
          "sha256": "e0aeb0522f68d0fa6e7fe98d8504f7d2a905c22802353904ab94d0e8de0a35a3",
          "sha1": "4088593f3a3e32b7079b2e79764dd813ae26d2c1",
          "md5": "d79e43610995f598c93b1b1da4cff62b"
        }
      ]
    }
  ]
}
