{
  "formatVersion": "1.1",
  "component": {
    "group": "de.kwerber.ghpub",
    "module": "plugin",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-0.1.jar",
          "url": "plugin-0.1.jar",
          "size": 17135,
          "sha512": "11dc2566503e7ae8405d2bb6701b44712910704574b436bbafb804a9a4395f515ba5bef330adce8a1f1707acc23b377f75615e6acbf2be3d0dfc2f0ee4eca8c6",
          "sha256": "9cec8c390cb25be582d1f1c96c091e1555182794c589d69fe02bffab6209d9e3",
          "sha1": "2357b499ef9c92339f3f52034dcaf919949fcdd0",
          "md5": "47a6f17b98a2b06dde676c10a9e833ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.4.31"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.1.jar",
          "url": "plugin-0.1.jar",
          "size": 17135,
          "sha512": "11dc2566503e7ae8405d2bb6701b44712910704574b436bbafb804a9a4395f515ba5bef330adce8a1f1707acc23b377f75615e6acbf2be3d0dfc2f0ee4eca8c6",
          "sha256": "9cec8c390cb25be582d1f1c96c091e1555182794c589d69fe02bffab6209d9e3",
          "sha1": "2357b499ef9c92339f3f52034dcaf919949fcdd0",
          "md5": "47a6f17b98a2b06dde676c10a9e833ed"
        }
      ]
    }
  ]
}
