{
  "formatVersion": "1.1",
  "component": {
    "group": "de.kwerber",
    "module": "persistlib",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "javax.persistence",
          "module": "javax.persistence-api",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "persistlib-0.4.5.jar",
          "url": "persistlib-0.4.5.jar",
          "size": 63097,
          "sha512": "4b0b960f44175c66c9aa785ffc7a095f4414226b3d1b9f5e27d43410c996e9269a4e96e89b42e877a7bf1c66676798a7675d6c3a2a32559d3d13bec659baa42c",
          "sha256": "e8d80c8fda85a0633fc31a2f94ee198bdb6efb70550891cb027aaa15b2ea1201",
          "sha1": "caed74d38d80c91b83d816d88f4a1a0c41839b6a",
          "md5": "5a2234417a7508e250f788058343054c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.vorburger.mariaDB4j",
          "module": "mariaDB4j",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.mariadb.jdbc",
          "module": "mariadb-java-client",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "javax.persistence",
          "module": "javax.persistence-api",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "persistlib-0.4.5.jar",
          "url": "persistlib-0.4.5.jar",
          "size": 63097,
          "sha512": "4b0b960f44175c66c9aa785ffc7a095f4414226b3d1b9f5e27d43410c996e9269a4e96e89b42e877a7bf1c66676798a7675d6c3a2a32559d3d13bec659baa42c",
          "sha256": "e8d80c8fda85a0633fc31a2f94ee198bdb6efb70550891cb027aaa15b2ea1201",
          "sha1": "caed74d38d80c91b83d816d88f4a1a0c41839b6a",
          "md5": "5a2234417a7508e250f788058343054c"
        }
      ]
    }
  ]
}
